export const UI_TEXT = {
  sidebar: {
    subtitle: 'Central de Controle Operacional',
  },
  menu: {
    operations: 'Operação do Dia',
    trips: 'Importar Operação',
    routes: 'Rotas',
    patients: 'Pacientes',
    vehicles: 'Frota',
    drivers: 'Motoristas',
    alerts: 'Replay Operacional',
    reports: 'Relatórios',
    settings: 'Configurações',
    messageTemplates: 'Templates de Mensagens',
  },
  topBar: {
    homologationBanner: 'MODO HOMOLOGAÇÃO · OPERAÇÕES SIMULADAS',
    operations: 'Operações',
    liveClock: 'Relógio em tempo real',
    realtimeOnline: 'Tempo real online',
    realtimeOffline: 'Tempo real offline',
    connected: '● Conectado',
    offline: '○ Offline',
    operator: 'Operador',
    logout: 'Sair',
  },
  dashboard: {
    overline: 'PRAEM OPS · central operacional em tempo real',
    title: 'Operações do dia',
    description:
      'Visibilidade em tempo real de despacho, logística de pacientes, execução de rotas e alertas operacionais.',
    realtimeConnected: 'Tempo real conectado',
    realtimeOffline: 'Tempo real offline',
    routesTracked: 'rotas monitoradas',
    boardingEvents: 'eventos de embarque',
    activeOperations: 'Operações ativas',
    routesLive: 'Rotas ativas',
    alerts: 'Alertas',
    inTransit: 'Em trânsito',
    waitingBoarding: 'Aguardando embarque',
    kpiOperationsToday: 'Operações do dia',
    kpiVehiclesInTransit: 'Veículos em trânsito',
    kpiWaitingPatients: 'Pacientes aguardando embarque',
    kpiCriticalAlerts: 'Alertas críticos',
  },
  operationalRail: {
    upcomingPickups: 'Próximos embarques',
    livePickupWindows: 'janelas ativas de embarque',
    noPickupWindows: 'Sem janelas de embarque no momento.',
    etaLive: 'ETA ao vivo',
    etaNow: 'ETA agora',
    destination: 'Destino',
    criticalAlerts: 'Alertas críticos',
    activeSignals: 'sinais ativos',
    noCriticalAlerts: 'Sem alertas críticos no momento.',
    fleetStatus: 'Status da frota',
    connected: 'conectados',
    moving: 'Em movimento',
    boarding: 'Embarcando',
    offline: 'Offline',
    live: 'Ao vivo',
    noVehiclesReporting: 'Nenhum veículo reportando ainda.',
    driverPending: 'Motorista pendente',
    tracking: 'rastreamento',
    stale: 'desatualizado',
  },
  operationalMap: {
    etaLive: 'ETA ao vivo',
    etaNow: 'ETA agora',
    destination: 'Destino',
    patientPrefix: 'Paciente',
    pickupWindow: 'Janela de embarque',
    panelOverline: 'Mapa em tempo real',
    panelTitle: 'Movimento da frota, embarques e execução de rotas',
    realtimeConnected: 'Tempo real conectado',
    realtimeOffline: 'Tempo real offline',
    followOn: 'Acompanhar ligado',
    followOff: 'Acompanhar desligado',
    vehiclesLive: 'veículos ao vivo',
    pickupWindows: 'janelas de embarque',
    fleetSnapshot: 'Panorama da frota',
    waitingGps: 'Aguardando telemetria de GPS.',
    driverPending: 'Motorista pendente',
    speed: 'Velocidade',
    updated: 'Atualizado',
  },
};
